@CryptoTickerBotAPI_HostAddress = http://localhost:5196

GET {{CryptoTickerBotAPI_HostAddress}}/todos/
Accept: application/json

###

GET {{CryptoTickerBoAPI_HostAddress}}/todos/1
Accept: application/json

###
